In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [9]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr / arr

C:\Users\obayd\AppData\Local\Temp\ipykernel_14196\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1 / 0

ZeroDivisionError: division by zero

In [14]:
1 / arr

C:\Users\obayd\AppData\Local\Temp\ipykernel_14196\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
2/arr

C:\Users\obayd\AppData\Local\Temp\ipykernel_14196\2607575421.py:1: RuntimeWarning: divide by zero encountered in divide
  2/arr


array([       inf, 2.        , 1.        , 0.66666667, 0.5       ,
       0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222])

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.sum()

np.int64(45)

In [18]:
arr.max()

np.int64(9)

In [19]:
arr.var()

np.float64(8.25)

In [20]:
arr.std()

np.float64(2.8722813232690143)

In [24]:
arrs= np.arange(0,25).reshape (5,5)

In [25]:
arrs

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arrs.sum()

np.int64(300)

In [27]:
arrs.sum(axis=0)

array([50, 55, 60, 65, 70])

In [28]:
arrs.sum(axis = 1)

array([ 10,  35,  60,  85, 110])