In [3]:
import numpy as np
Habib =[1,2,3]
type(Habib)

list

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
len(np.linspace(0, 5, 21))

21

In [2]:
np.eye(4)

NameError: name 'np' is not defined

In [4]:
slice_of_arr[:] = 99

NameError: name 'slice_of_arr' is not defined

In [5]:
slice_of_arr

NameError: name 'slice_of_arr' is not defined

In [8]:
import numpy as np
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:5]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [19]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [22]:
arr_copy = arr.cop()

AttributeError: 'numpy.ndarray' object has no attribute 'cop'

In [23]:
bool_arr = arr>4


In [24]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])